"""metal_rolls

Revision ID: 18bfaf650f8e
Revises: 
Create Date: 2025-03-15 22:10:02.912495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18bfaf650f8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_metal_rolls_id', table_name='metal_rolls')
    op.drop_table('metal_rolls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metal_rolls',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('added_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('removed_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='metal_rolls_pkey')
    )
    op.create_index('ix_metal_rolls_id', 'metal_rolls', ['id'], unique=False)
    # ### end Alembic commands ###
